import {createContext,useContext,useEffect,useRef,useState,ReactNode} from 'react';
import './project.css';
import './native.css';
import {AddAction} from './AddAction';
import {VideoOverlay} from './VideoOverlay';
import './event-tools.css';
export type Action={id?:number;name:string;detail:string;at:number;result?:string;failed?:boolean;executable?:boolean;x?:number;y?:number;text?:string;kind?:string;label?:string;captureLeft?:number;captureTop?:number;captureWidth?:number;captureHeight?:number};
type NativeState={busy:boolean;phase:string;message:string;timer?:string;source?:string;name?:string;projectPath?:string;width?:number;height?:number;iteration?:number;total?:number;events:Action[]};
type Shell={desktop:boolean;setMode:(mode:string)=>Promise<unknown>;command:(action:string,data?:unknown)=>Promise<void>;getState:()=>Promise<NativeState>;onState:(callback:(state:NativeState)=>void)=>()=>void};
export const shell=(window as Window & {axShell?:Shell}).axShell;
function useProjectState(){
 const [cursor,setCursor]=useState(0),[source,setSource]=useState(''),[name,setName]=useState('새 업무'),[events,setEvents]=useState<Action[]>([]),[repeats,setRepeats]=useState(1),[mode,setMode]=useState<'studio'|'compact'>('compact');
 const [native,setNative]=useState<NativeState>({busy:false,phase:shell?'connecting':'browser',message:shell?'엔진 연결 중':'녹화·자동화는 Electron 앱에서 실행하세요.',events:[]}),[error,setError]=useState(''),[pending,setPending]=useState(false);
 useEffect(()=>{if(!shell)return;const receive=(s:NativeState)=>{setNative(s);setEvents(s.events);setSource(s.source||'');setName(s.name||'새 업무');};const off=shell.onState(receive);shell.getState().then(receive).catch(e=>setError(String(e)));return off;},[]);
 useEffect(()=>()=>{if(source.startsWith('blob:'))URL.revokeObjectURL(source);},[source]);
 const loadVideo=(file:File)=>{setSource(URL.createObjectURL(file));setName(file.name);setEvents([]);setCursor(0);};
 const command=async(action:string,data?:unknown)=>{setError('');if(!shell){setError('Electron 앱에서 사용할 수 있습니다.');return false;}setPending(true);try{await shell.command(action,data);return true;}catch(e){setError(e instanceof Error?e.message:String(e));return false;}finally{setPending(false);}};
 return {cursor,setCursor,source,name,events,repeats,setRepeats,mode,setMode,loadVideo,native,error,command,busy:native.busy||pending,connected:!!shell&&native.phase!=='error'&&native.phase!=='connecting'};
}
type Project=ReturnType<typeof useProjectState>;
const Context=createContext<Project|null>(null);
export function ProjectProvider({children}:{children:ReactNode}){return <Context.Provider value={useProjectState()}>{children}</Context.Provider>;}
export function useProject(){return useContext(Context)!;}
export function RepeatSettings(){const p=useProject();return <div className="repeat-settings"><label>반복 횟수 <input aria-label="반복 횟수" disabled={p.busy} type="number" min={1} max={999} step={1} value={p.repeats} onChange={e=>p.setRepeats(Math.min(999,Math.max(1,Math.floor(Number(e.target.value)||1))))}/> 회</label><span>3초 후 시작 · Ctrl + Shift + F12 중지</span></div>;}
export function ProjectToolbar(){const p=useProject();const file=useRef<HTMLInputElement>(null);return <section className="native-controls">
 <div className="native-buttons"><button className="primary" disabled={p.busy||!p.connected} onClick={()=>p.command('record')}>● 업무 보여주기</button><button disabled={p.busy||!p.connected||!p.events.some(e=>e.executable)} onClick={()=>p.command('run',{repeats:p.repeats})}>▶ 실행</button><button className="stop-button" disabled={!p.native.busy} onClick={()=>p.command('stop')}>■ 중지</button><button disabled={p.busy} onClick={()=>shell?p.command('open'):file.current?.click()}>열기</button><button disabled={p.busy||!p.connected||!p.source} onClick={()=>p.command('save')}>저장</button></div>
 <input className="sr" type="file" accept="video/*" ref={file} onChange={e=>{if(e.target.files?.[0])p.loadVideo(e.target.files[0]);e.target.value='';}}/>
 <RepeatSettings/><div className="engine-status" role="status"><span className={'status-dot '+(p.native.busy?'active':'')}/><strong>{p.native.message}</strong><span>{p.native.timer}</span>{p.native.phase==='running'&&<span>{p.native.iteration}/{p.native.total}회</span>}</div>
 {p.error&&<p className="native-error" role="alert">{p.error}</p>}
 <details className="native-help"><summary>작업 안내</summary><p>주 모니터의 영상·클릭·드래그·스크롤·키 입력을 기록합니다. 시작 시 창이 최소화됩니다. 종료: Ctrl + Shift + F12.</p><p>좌표 기반 재생: 창 위치·화면 배율·입력 언어를 시연 때와 같게 맞추세요. 실행 전 대상을 선택하세요.</p><p>녹화·반복 실행 중 CPU·GPU·디스크 사용량이 증가해 PC가 느려질 수 있습니다. 암호 입력은 기록하지 마세요.</p>{p.native.width&&<p>기록 화면 {p.native.width} × {p.native.height} · 주 모니터</p>}{p.native.projectPath&&<p className="save-path">저장 위치: {p.native.projectPath}</p>}</details>
 </section>;}
export function EventList(){const p=useProject();const [editing,setEditing]=useState<number|null>(null);const [at,setAt]=useState('0'),[x,setX]=useState(''),[y,setY]=useState(''),[seconds,setSeconds]=useState('2'),[text,setText]=useState('');
 return <><AddAction/><div className="real-events">{p.events.map((a,i)=><div className={'real-event '+(a.failed?'failed':'')} key={i}><button className="event-seek" onClick={()=>p.setCursor(a.at)}><span className="event-index">{String(i+1).padStart(2,'0')}</span><span><b>{a.name}</b><small>{a.detail}</small>{a.x!=null&&<small>좌표 {a.x}, {a.y}</small>}{a.result&&<small>{a.result}</small>}</span><time>{a.at.toFixed(1)}s</time></button><button className="edit-trigger" disabled={p.busy||!p.connected} aria-label={String(i+1)+'번 행동 수정'} onClick={()=>{setEditing(editing===i?null:i);setAt(String(a.at));setSeconds(a.text||'2');setText(a.text||'');setX(String(a.x??''));setY(String(a.y??''));}}>수정</button>{editing===i&&<form className="event-edit" onSubmit={e=>{e.preventDefault();p.command('edit',{index:i,at:Number(at),...(a.kind==='Wait'?{seconds:Number(seconds)}:{}),...(a.kind==='TextEntry'?{text}:{}),...(x!==''?{x:Number(x),y:Number(y)}:{})});setEditing(null);}}><label>시간(초)<input required type="number" min="0" max="86400" step=".01" value={at} onChange={e=>setAt(e.target.value)}/></label>{a.x!=null&&<><label>X<input required type="number" value={x} onChange={e=>setX(e.target.value)}/></label><label>Y<input required type="number" value={y} onChange={e=>setY(e.target.value)}/></label></>}{a.kind==='Wait'&&<label>대기(초)<input required type="number" min=".1" max="3600" step=".1" value={seconds} onChange={e=>setSeconds(e.target.value)}/></label>}{a.kind==='TextEntry'&&<label>입력 내용<input required value={text} maxLength={10000} onChange={e=>setText(e.target.value)}/></label>}<button disabled={p.busy}>적용</button><button disabled={p.busy} type="button" onClick={()=>{p.command('delete',{index:i});setEditing(null);}}>삭제</button></form>}</div>)}{!p.events.length&&<p className="empty-events">기록된 행동이 없습니다.</p>}</div></>;
}
export function SharedVideo({view}:{view:'studio'|'compact'}){const p=useProject();const ref=useRef<HTMLVideoElement>(null);const [error,setError]=useState(''),[showOverlay,setShowOverlay]=useState(true);
 useEffect(()=>{const v=ref.current;if(!v)return;if(p.mode!==view)v.pause();else if(Number.isFinite(v.duration)&&Math.abs(v.currentTime-p.cursor)>.5)v.currentTime=Math.min(p.cursor,v.duration);},[p.mode,p.cursor,view]);
 useEffect(()=>setError(''),[p.source]);
 return <div className="shared-video"><div className="video-surface"><video ref={ref} src={p.source} controls controlsList="nofullscreen" playsInline preload="metadata" aria-label="업무 영상" onSeeked={()=>{if(p.mode===view&&ref.current)p.setCursor(ref.current.currentTime);}} onTimeUpdate={()=>{if(p.mode===view&&ref.current)p.setCursor(ref.current.currentTime);}} onError={()=>setError('영상 재생 실패: 파일 형식과 저장 상태를 확인하세요.')}/>{showOverlay&&<VideoOverlay video={ref} events={p.events} cursor={p.cursor}/>}</div><div className="video-overlay-controls"><button type="button" aria-pressed={showOverlay} onClick={()=>setShowOverlay(!showOverlay)}>동작 표시 {showOverlay?'켜짐':'꺼짐'}</button><button type="button" onClick={()=>{ref.current?.parentElement?.requestFullscreen().catch(()=>setError('전체 화면 전환 실패'));}}>전체 화면</button></div>{error&&<p role="alert">{error}</p>}</div>;
}
